#!/bin/sh
set -e

until PGPASSWORD=$POSTGRES_PASSWORD psql -h "$POSTGRES_HOST" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c '\q'; do
  echo "Waiting for Postgres..."
  sleep 1
done

echo "Applying database migrations..."
python manage.py migrate --settings=config.settings.local --noinput


echo "Collecting static files..."
python manage.py collectstatic --settings=config.settings.local --noinput

exec "$@"
