volumes:
  media_data:
  read_hub_postgres_data:
  read_hub_redis_data:

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: read_hub_django
    image: read_hub_image:local
    volumes:
      - ./src:/app/src
      - media_data:/app/src/media
    depends_on:
      - redis
      - postgres
    env_file:
      - ./.env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - read-hub-local-network

  postgres:
    image: postgres:13
    container_name: read_hub_postgres
    volumes:
      - read_hub_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - read-hub-local-network

  redis:
    image: redis:6
    container_name: read_hub_redis
    volumes:
      - read_hub_redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - read-hub-local-network

networks:
  read-hub-local-network:
    driver: bridge
