# Generated by Django 5.2.1 on 2025-08-28 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="is_active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="modified_at")),
                ("name", models.CharField(unique=True)),
                ("duration_days", models.IntegerField()),
                ("price", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "membership plan",
                "verbose_name_plural": "membership plans",
            },
        ),
        migrations.CreateModel(
            name="PurchasedMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="is_active")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="modified_at")),
                ("price_paid", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "purchased membership",
                "verbose_name_plural": "purchased memberships",
            },
        ),
        migrations.CreateModel(
            name="UserDiscount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="is_active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="modified_at")),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("promo_code", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "user discount",
                "verbose_name_plural": "user discounts",
            },
        ),
        migrations.CreateModel(
            name="Preorder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="is_active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="modified_at")),
                (
                    "membership_plan",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="membership.membershipplan"),
                ),
            ],
            options={
                "verbose_name": "preorder",
                "verbose_name_plural": "preorders",
            },
        ),
    ]
