# Generated by Django 5.2.1 on 2025-08-28 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("membership", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="preorder",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="purchasedmembership",
            name="preorder",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="membership.preorder"),
        ),
        migrations.AddField(
            model_name="userdiscount",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="preorder",
            name="user_discount",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="membership.userdiscount"
            ),
        ),
    ]
