# Generated by Django 5.2.1 on 2025-08-28 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookContributor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="is_active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="modified_at")),
                ("full_name", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "book_contributor",
                "verbose_name_plural": "book_contributors",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="is_active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="modified_at")),
                ("name", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="is_active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="modified_at")),
                ("name", models.CharField(max_length=200)),
                ("publisher", models.CharField(max_length=200)),
                ("auther", models.ManyToManyField(related_name="author_books", to="book.bookcontributor")),
                ("translator", models.ManyToManyField(related_name="translator_books", to="book.bookcontributor")),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="book.category")),
            ],
            options={
                "verbose_name": "book",
                "verbose_name_plural": "books",
                "default_related_name": "books",
            },
        ),
    ]
