#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python src/manage.py migrate
python src/manage.py collectstatic --noinput

export PYTHONPATH="./src"

echo "starting gunicorn"
exec python -m gunicorn -c deployments/gunicorn_conf/gunicorn.development.conf.py config.wsgi:application
